<a href="https://colab.research.google.com/github/pranav19611/EDS/blob/main/practice12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1=np.array([[2,3,5],[1,9,8],[4,7,5]])
arr1

array([[2, 3, 5],
       [1, 9, 8],
       [4, 7, 5]])

In [ ]:
arr2=np.array([[11,56,98],[32,19,44],[66,98,21]])
arr2

array([[11, 56, 98],
       [32, 19, 44],
       [66, 98, 21]])

In [ ]:
resultarr=np.divide(arr1,arr2)
print(resultarr)

[[0.18181818 0.05357143 0.05102041]
 [0.03125    0.47368421 0.18181818]
 [0.06060606 0.07142857 0.23809524]]


In [ ]:
resultmulti=np.multiply(arr1,arr2)
print(resultmulti)

[[ 22 168 490]
 [ 32 171 352]
 [264 686 105]]


In [ ]:
resultadd=np.add(arr1,arr2)
print(resultadd)

[[ 13  59 103]
 [ 33  28  52]
 [ 70 105  26]]


In [ ]:
c=np.stack((arr1,arr2),axis=0)
print(c)

[[[ 2  3  5]
  [ 1  9  8]
  [ 4  7  5]]

 [[11 56 98]
  [32 19 44]
  [66 98 21]]]


In [ ]:
d=np.stack((arr1,arr2),axis=1)
print(d)

[[[ 2  3  5]
  [11 56 98]]

 [[ 1  9  8]
  [32 19 44]]

 [[ 4  7  5]
  [66 98 21]]]


In [ ]:
np.transpose(arr1)


array([[2, 1, 4],
       [3, 9, 7],
       [5, 8, 5]])

In [ ]:
np.transpose(arr2)

array([[11, 32, 66],
       [56, 19, 98],
       [98, 44, 21]])

In [ ]:
np.arange(start=3,stop=13,step=3)

array([ 3,  6,  9, 12])

In [ ]:
print(arr1.shape)

(3, 3)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
